/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.University;

import business.Applicant.Applicant;
import business.Organization.UniversityOrganization;
import business.University.Major;
import business.UserAccount.UserAccount;
import business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author sahil
 */
public class ProfessorManageStudent extends javax.swing.JPanel {

    /**
     * Creates new form TeacherManageStudent
     */
    
    UserAccount userAccount;
    UniversityOrganization universityOrganization;
    Major major;
    ArrayList<Applicant> applicantList;
    Applicant applicant;
    
    public ProfessorManageStudent(UserAccount userAccount,
            UniversityOrganization universityOrganization) {
        initComponents();
        this.userAccount = userAccount;
        this.universityOrganization = universityOrganization;
        applicantList = new ArrayList();
        populateCourseCombo();
    }
    
    public void populateCourseCombo() {
        cbCourse.removeAllItems();
        
        for (Major m: universityOrganization.getUniversity().getMajorList()) {
            if (m.getProfessor() == userAccount) {
                cbCourse.addItem(m);
            }
        }
    }
    
    public void populateStudentCombo() {
        cbStudent.removeAllItems();
        
        major = (Major) cbCourse.getSelectedItem();
        for (WorkRequest w: universityOrganization.getWorkQueue().getWorkRequestList()) {
            if ((Major)w.getSubject() == major && w.getStatus().equals("Offer Accepted")) {
                cbStudent.addItem(w.getSender().getId() + " - " + w.getSender().getPerson().getName());
                applicantList.add(w.getSender());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        cbCourse = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGrade = new javax.swing.JTextField();
        btnUpdae = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        cbStudent = new javax.swing.JComboBox<>();

        kGradientPanel1.setkStartColor(new java.awt.Color(102, 204, 255));

        cbCourse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbCourseMousePressed(evt);
            }
        });
        cbCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCourseActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Course");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Student");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student Name");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Student Score");

        txtGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradeActionPerformed(evt);
            }
        });

        btnUpdae.setBackground(new java.awt.Color(153, 255, 102));
        btnUpdae.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdae.setText("Update");
        btnUpdae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdaeActionPerformed(evt);
            }
        });

        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText(".");

        cbStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbStudentMousePressed(evt);
            }
        });
        cbStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(534, 534, 534)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCourse, 0, 154, Short.MAX_VALUE)
                    .addComponent(cbStudent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(544, 544, 544))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(518, 518, 518)
                .addComponent(btnUpdae, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66)
                .addComponent(btnUpdae, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(532, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1298, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 887, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCourseActionPerformed
        // TODO add your handling code here:
        populateStudentCombo();              
    }//GEN-LAST:event_cbCourseActionPerformed

    private void btnUpdaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdaeActionPerformed
        // TODO add your handling code here:       
        applicant.getEducationList().get(1).setGrade(
                Double.parseDouble(txtGrade.getText()));
        
        JOptionPane.showMessageDialog(this, "Score Updated.");
        return;
        
    }//GEN-LAST:event_btnUpdaeActionPerformed

    private void txtGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradeActionPerformed
        // TODO add your handling code here:
//        radiodisplay();
//        int rank = 1;
//        for(int i=0;i<studentcoursesarray.getStudentCoursesArray().size();i++){
//            for(int j=0;j<studentcoursesarray.getStudentCoursesArray().size();j++){
//                if(i!=j && studentcoursesarray.getStudentCoursesArray().get(i).getCourseScore() < studentcoursesarray.getStudentCoursesArray().get(j).getCourseScore()){
//                    rank++;
//                }
//            }
//            studentcoursesarray.getStudentCoursesArray().get(i).setStudentCourseRank(rank);
//            rank = 1;
//        }
    }//GEN-LAST:event_txtGradeActionPerformed

    private void cbStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStudentActionPerformed

    private void cbCourseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCourseMousePressed
        // TODO add your handling code here:
        populateStudentCombo();
    }//GEN-LAST:event_cbCourseMousePressed

    private void cbStudentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbStudentMousePressed
        // TODO add your handling code here:
        int applicantId = Integer.parseInt(
                cbStudent.getSelectedItem().toString().split(" - ")[0]);
        
        for (Applicant a: applicantList) {
            if (a.getId() == applicantId) {
                applicant = a;
                break;
            }
        }
        
        lblName.setText(applicant.toString());
    }//GEN-LAST:event_cbStudentMousePressed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdae;
    private javax.swing.JComboBox<Major> cbCourse;
    private javax.swing.JComboBox<String> cbStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txtGrade;
    // End of variables declaration//GEN-END:variables

    

    
}
