    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Dashboards;

import business.Organization.UniversityOrganization;
import business.University.Major;
import business.WorkQueue.WorkRequest;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Set;
import javax.swing.ImageIcon;
import models.DashboardModel_card;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author sahil
 */
public class UniversityAdminDashboard extends javax.swing.JPanel {

    /**
     * Creates new form TeacherOverviewPanel1
     */
//    private Map<String, Integer> countryCount = new HashMap<>();
//    private Map<String, Integer> countryCount1 = new HashMap<>();
//    
    UniversityOrganization uo;
    public UniversityAdminDashboard(UniversityOrganization uo) {
        initComponents();
        this.uo = uo;
//        this.countryCount = new HashMap<>();
//        this.countryCount1 = new HashMap<>();
        
        displaymetrics();
        bar_chart();
        line_chart();
        displayCharts();
//        table_content();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panelBarChart = new models.PanelBorder();
        jPanel2 = new javax.swing.JPanel();
        dashboardCard1 = new models.DashboardCard();
        dashboardCard2 = new models.DashboardCard();
        dashboardCard3 = new models.DashboardCard();
        panelBorder1 = new models.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();

        setOpaque(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(1400, 1080));

        panelBarChart.setBackground(new java.awt.Color(204, 204, 204));
        panelBarChart.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 10, 1));

        dashboardCard1.setColor1(new java.awt.Color(153, 102, 255));
        dashboardCard1.setColor2(new java.awt.Color(255, 102, 102));
        jPanel2.add(dashboardCard1);

        dashboardCard2.setColor1(new java.awt.Color(153, 102, 255));
        dashboardCard2.setColor2(new java.awt.Color(255, 102, 102));
        jPanel2.add(dashboardCard2);

        dashboardCard3.setColor1(new java.awt.Color(153, 102, 255));
        dashboardCard3.setColor2(new java.awt.Color(255, 102, 102));
        jPanel2.add(dashboardCard3);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("University Courses");

        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course Name", "Total Applicants"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCourse.setOpaque(false);
        jScrollPane2.setViewportView(tblCourse);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(panelBarChart, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBarChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private models.DashboardCard dashboardCard1;
    private models.DashboardCard dashboardCard2;
    private models.DashboardCard dashboardCard3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private models.PanelBorder panelBarChart;
    private models.PanelBorder panelBorder1;
    private javax.swing.JTable tblCourse;
    // End of variables declaration//GEN-END:variables
    
    private void bar_chart() {
        List<String> coursenames = new ArrayList<>();
        List<Integer> studentspercourse = new ArrayList<>();
        
//        for(TeacherMyCourses teachermycourses: teachermycoursesarray.getTeacherMyCoursesArray()){
//            if(teachermycourses.getTeacherUsername().equals(teacherusername)){
//                coursenames.add(teachermycourses.getCourseName());
//                studentspercourse.add(teachermycourses.getStudentsRegistered());
//                }
//        }
//                    
//        
//        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
//        
//        for(int i=0;i<coursenames.size();i++){
//            dataset.setValue(studentspercourse.get(i), "Students Registered", coursenames.get(i));
//        }
//        dataset.setValue(80, "Students Registered", "Course 1");
//        dataset.setValue(50, "Students Registered", "Course 2");
//        dataset.setValue(60, "Students Registered", "Course 3");
//        dataset.setValue(20, "Students Registered", "Course 4");
        
//        JFreeChart barchart = ChartFactory.createBarChart("Students Per Course", "My Courses", "Students Registered", dataset,PlotOrientation.VERTICAL,false,true,false);
//        CategoryPlot p = barchart.getCategoryPlot();
//        barchart.setBackgroundPaint(Color.white);
//        
//        BarRenderer renderer = (BarRenderer) p.getRenderer();
//        Color color = new Color(79, 120, 240);
//        renderer.setSeriesPaint(1, color);
//        
//        ChartPanel barChartPanel = new ChartPanel(barchart);
//        panelBarChart.removeAll();
//        panelBarChart.add(barChartPanel);
//        panelBarChart.validate();

        HashMap<String, Integer> majorCountMap = new HashMap();
        Major m;
        String major;
        for(WorkRequest w: uo.getWorkQueue().getWorkRequestList()) {
            m = (Major) w.getSubject();
            major = m.getName();
            if (majorCountMap.containsKey(major)) 
                majorCountMap.put(major, majorCountMap.get(major) + 1);
            else
                majorCountMap.put(major, 1);
        }
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        for (Map.Entry<String, Integer> entry : majorCountMap.entrySet()) {
            String key = entry.getKey();
            int value = entry.getValue();
            dataset.setValue(value, "Students Applied", key);
        }
        
        JFreeChart barchart = ChartFactory.createBarChart(
                "Major vs Students Applied Chart", "Major Name", 
                "Students Applied", dataset,PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p = barchart.getCategoryPlot();
        barchart.setBackgroundPaint(Color.white);
        p.setBackgroundPaint(null);
        
        BarRenderer renderer = (BarRenderer) p.getRenderer();
        Color color = new Color(41,134,204);
        renderer.setSeriesPaint(1, color);
        
        ChartPanel barChartPanel = new ChartPanel(barchart);
        panelBarChart.removeAll();
        panelBarChart.add(barChartPanel);
        panelBarChart.validate();
    }
    
    private void earning_chart() {
//        List<String> coursenames = new ArrayList<>();
//        List<Integer> earnings = new ArrayList<>();
//        
//        for(TeacherMyCourses teachermycourses: teachermycoursesarray.getTeacherMyCoursesArray()){
//            if(teachermycourses.getTeacherUsername().equals(teacherusername)){
//                coursenames.add(teachermycourses.getCourseName());
//                earnings.add(teachermycourses.getStudentsRegistered()*teachermycourses.getCoursePrice());
//                }
//        }
//                    
//        
//        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
//        
//        for(int i=0;i<coursenames.size();i++){
//            dataset.setValue(earnings.get(i), "Students Registered", coursenames.get(i));
//        }
//        dataset.setValue(80, "Students Registered", "Course 1");
//        dataset.setValue(50, "Students Registered", "Course 2");
//        dataset.setValue(60, "Students Registered", "Course 3");
//        dataset.setValue(20, "Students Registered", "Course 4");
        
//        JFreeChart barchart = ChartFactory.createBarChart("Earnings Per Course", "My Courses", "Course Earnings", dataset,PlotOrientation.VERTICAL,false,true,false);
//        CategoryPlot p = barchart.getCategoryPlot();
//        barchart.setBackgroundPaint(Color.white);
//        
//        BarRenderer renderer = (BarRenderer) p.getRenderer();
//        Color color = new Color(79, 120, 240);
//        renderer.setSeriesPaint(1, color);
//        
//        ChartPanel barChartPanel = new ChartPanel(barchart);
//        panelBarChart.removeAll();
//        panelBarChart.add(barChartPanel);
//        panelBarChart.validate();
    }

    private void line_chart() {
//        List<String> totalhired = new ArrayList<>();
//        List<Integer> month = new ArrayList<>();
//        
//        for(TeacherMyCourses teachermycourses: teachermycoursesarray.getTeacherMyCoursesArray()){
//            if(teachermycourses.getTeacherUsername().equals(teacherusername)){
//                coursenames.add(teachermycourses.getCourseName());
//                earnings.add(teachermycourses.getStudentsRegistered()*teachermycourses.getCoursePrice());
//                }
//        }
//                    
//        
//        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
//        
//        for(int i=0;i<coursenames.size();i++){
//            dataset.setValue(earnings.get(i), "Students Registered", coursenames.get(i));
//        }
//        
//        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
//        dataset.setValue(80, "Applications", "January");
//        dataset.setValue(150, "Applications", "February");
//        dataset.setValue(60, "Applications", "March");
//        dataset.setValue(20, "Applications", "April");
//        
//        JFreeChart linechart = ChartFactory.createLineChart("Application Statistics", "Number of Applications","Month", dataset, PlotOrientation.VERTICAL,false,true,false);
//        CategoryPlot lineCategoryPlot = linechart.getCategoryPlot();
//        lineCategoryPlot.setBackgroundPaint(Color.white);
//        
//        LineAndShapeRenderer lineRenderer = (LineAndShapeRenderer) lineCategoryPlot.getRenderer();
//        Color lineCharColor = new Color(204,0,51);
//        lineRenderer.setSeriesPaint(0, lineCharColor);
//        
//        ChartPanel lineChartPanel = new ChartPanel(linechart);
//        panelLineChart.removeAll();
//        panelLineChart.add(lineChartPanel);
//        panelLineChart.validate();
//        
    }

//    private void table_content() {
//        tblCourse
//    }
    
    private void displayCharts(){
//        
//        
//        for(int i=0; i<studentprofilearray.getStudentProfileArray().size(); i++){
//            
//            String countryName = studentprofilearray.getStudentProfileArray().get(i).getStudentCountry();
//            
//            if(countryCount.containsKey(countryName)){
//                
//                countryCount.put(countryName, countryCount.get(countryName) + 1);
//             
//            }
//            
//            else{
//            
//                countryCount.put(countryName, 1);
//                
//            }
//                
//            
//        }
//        
//        Set<String> keys =  countryCount.keySet();
//        String[] keyArray = keys.toArray(new String[0]);
//        Random random = new Random();
//
//        PieChart pieChart = new PieChart();
//        pieChart.setChartType(PieChart.PeiChartType.DONUT_CHART);
//                
//        for(int i=0; i<countryCount.size(); i++){
//      
//            Color randomColor = new Color(random.nextInt(256), random.nextInt(256), random.nextInt(256));
//            ModelPieChart country = new ModelPieChart(keyArray[i], countryCount.get(keyArray[i]), randomColor);
//            pieChart.addData(country);
//            
//        }
//        
//        
//        ModelPieChart country2 = new ModelPieChart("Label 2", 40, Color.YELLOW);
//        ModelPieChart country3 = new ModelPieChart("Label 3", 20, Color.GREEN);
//
//        jPanel4.add(pieChart);
//        jPanel4.setVisible(true);
//        jPanel4.revalidate();
//        jPanel4.repaint();
//        
//                
//        for(int i=0; i<teacherprofilearray.getTeacherProfileArray().size(); i++){
//            
//            String countryName = teacherprofilearray.getTeacherProfileArray().get(i).getCountry();
//            
//            if(countryCount1.containsKey(countryName)){
//                
//                countryCount1.put(countryName, countryCount1.get(countryName) + 1);
//             
//            }
//            
//            else{
//            
//                countryCount1.put(countryName, 1);
//                
//            }
//                
//            
//        }
//        
//        Set<String> keys1 =  countryCount1.keySet();
//        String[] keyArray1 = keys1.toArray(new String[0]);
//        Random random1 = new Random();
//
//        PieChart pieChart1 = new PieChart();
//        pieChart1.setChartType(PieChart.PeiChartType.DONUT_CHART);
//                
//        for(int i=0; i<countryCount1.size(); i++){
//      
//            Color randomColor1 = new Color(random.nextInt(256), random.nextInt(256), random.nextInt(256));
//            ModelPieChart country1 = new ModelPieChart(keyArray1[i], countryCount1.get(keyArray1[i]), randomColor1);
//            pieChart1.addData(country1);
//            
//        }
//        
//        jPanel5.add(pieChart1);
//        jPanel5.setVisible(true);
//        jPanel5.revalidate();
//        jPanel5.repaint();
//        
    }
    
    private void displaymetrics() {
        
        int totalcourses = uo.getUniversity().getMajorList().size();        
        int totalstudents = 0;
        int totalapprovals = 0;
        
        for(WorkRequest w: uo.getWorkQueue().getWorkRequestList()){
            if(w.getStatus().equals("Offer Accepted") || w.getStatus().equals("Accepted")){
                totalapprovals += 1;
            }
            totalstudents += 1;
        }
//        
        dashboardCard1.setData(new DashboardModel_card(new ImageIcon(getClass().getResource("/images/courses.png")), "Total Courses", totalstudents));
        dashboardCard2.setData(new DashboardModel_card(new ImageIcon(getClass().getResource("/images/students.png")), "Total Applicants", totalcourses));
        dashboardCard3.setData(new DashboardModel_card(new ImageIcon(getClass().getResource("/images/univapproval.png")), "Applicants Accepted", totalapprovals));
//        
    }

}
    
