/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Student;

import business.Applicant.Applicant;
import business.Employer.JobRole;
import business.Organization.EmployerOrganization;
import business.UserAccount.UserAccount;
import business.WorkQueue.WorkRequest;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author sahil
 */
public class InsideJobApplication extends javax.swing.JPanel {

    /**
     * Creates new form InsideJobApplication
     */
    EmployerOrganization employerOrganization;
    UserAccount userAccount;
    JobRole jobRole;
    Applicant applicant;
    
    public InsideJobApplication(UserAccount userAccount, 
            EmployerOrganization employerOrganization, JobRole jobRole, 
            Applicant applicant) {
        initComponents();
        this.userAccount = userAccount;
        this.employerOrganization = employerOrganization;
        this.jobRole = jobRole;
        this.applicant = applicant;
        populateData();
        ifapplied();
    }

    public void populateData() {
        lblCompanyName.setText(employerOrganization.getEmployer().getName());
        lblJobRole.setText(jobRole.getName());
        lblJobId.setText(Integer.toString(jobRole.getId()));
        lblLocation.setText(jobRole.getLocation());
        lblJobRole.setText(jobRole.getName());
        txtDescription.setText(jobRole.getDescription());
        lblSalary.setText(Double.toString(jobRole.getPay()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        lblCompanyName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblJobId = new javax.swing.JLabel();
        lblteacherpic2 = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnApply = new javax.swing.JButton();
        lblCourseName5 = new javax.swing.JLabel();
        lblJobRole = new javax.swing.JLabel();
        lblteacherpic3 = new javax.swing.JLabel();
        lblSalary = new javax.swing.JLabel();

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        kGradientPanel3.setkStartColor(new java.awt.Color(102, 204, 255));

        lblCompanyName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCompanyName.setForeground(new java.awt.Color(255, 255, 255));
        lblCompanyName.setText("Company Name");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Job Id:");

        lblJobId.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblJobId.setForeground(new java.awt.Color(255, 255, 255));
        lblJobId.setText("JobId");

        lblteacherpic2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblteacherpic2.setForeground(new java.awt.Color(255, 255, 255));
        lblteacherpic2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblteacherpic2.setText("Location");

        lblLocation.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblLocation.setText("Location..");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Job Description");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane7.setViewportView(txtDescription);

        btnApply.setBackground(new java.awt.Color(0, 255, 0));
        btnApply.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        lblCourseName5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCourseName5.setForeground(new java.awt.Color(255, 255, 255));
        lblCourseName5.setText("Role: ");

        lblJobRole.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblJobRole.setForeground(new java.awt.Color(255, 255, 255));
        lblJobRole.setText("Role");

        lblteacherpic3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblteacherpic3.setForeground(new java.awt.Color(255, 255, 255));
        lblteacherpic3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblteacherpic3.setText("Salary:");

        lblSalary.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblSalary.setForeground(new java.awt.Color(255, 255, 255));
        lblSalary.setText("Salary..");

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblteacherpic2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCourseName5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblJobId, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                        .addComponent(lblJobRole, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblteacherpic3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(563, Short.MAX_VALUE))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJobRole, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJobId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblteacherpic2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblteacherpic3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(509, 509, 509))
        );

        jScrollPane6.setViewportView(kGradientPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1402, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1011, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        // TODO add your handling code here:
        WorkRequest request = new WorkRequest();
        request.setSender(applicant);
        request.setStatus("Applied");
        request.setSubject(jobRole);
        
        employerOrganization.getWorkQueue().getWorkRequestList().add(request);
        userAccount.getWorkQueue().getWorkRequestList().add(request);
        
        JOptionPane.showMessageDialog(this, "Applied Successfully.");
        btnApply.setText("Applied");
        btnApply.setBackground(Color.LIGHT_GRAY);
        btnApply.setEnabled(false);
    }//GEN-LAST:event_btnApplyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblCourseName5;
    private javax.swing.JLabel lblJobId;
    private javax.swing.JLabel lblJobRole;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblteacherpic2;
    private javax.swing.JLabel lblteacherpic3;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables

    private void ifapplied() {
//        for (WorkRequest w : userAccount.getWorkQueue().getWorkRequestList()){
//            if(w.getStatus().equals("Applied")){
//                btnApply.setText("Applied");
//                btnApply.setBackground(Color.LIGHT_GRAY);
//                btnApply.setEnabled(false);
//            }
//        }
    }
}
